### ISSUE TITLE
Support for 'Extended color light'

### ISSUE THREAD

**Issue by MikA2257** [dj95/huekit#9]
Hello,

I am using the `huekit` software with a Livarno light bulb from Lidl, and I have encountered an issue. It appears that the 'Extended color light' type is not currently supported. Here is the error message I received:

`{“level”:“info”,“msg”:“currently type: ‘Extended color light’ is not supported. Please create an issue, if you need support for it: https://github.com/dj95/huekit/issues”,“time”:“2023-10-25T18:53:35Z”}`

I would like to request support for this type of light, specifically for the Livarno brand from Lidl, in future versions of `huekit`. Could you please let me know if this is something that could be added?

Thank you for your time and assistance.

Best regards,

Mickaël

**Comment by dj95** [comment]
Hey @MikA2257 

sorry for the late reply.

Unfortunately I don't know, which capabilities the 'Extended color light' has because I don't own one. So for implementing it I need your help for testing it properly.

The latest commit added the functionality. Can you test it, please?
